### PR TITLE
Add default_redirection_url as configuration option

### PR DESCRIPTION
**Pull request by clems4ever**
This URL is used when user access the authentication domain without providing
the 'redirect' query parameter. In that case, Authelia does not know
where to redirect the user.
If the parameter is defined, Authelia can redirect the user to a default page
when no redirect parameter is provided.

When user is already authenticated and tries to access the authentication
domain, the "already logged in" page is rendered and it now tells the user he
is to be redirected in few seconds and uses this URL to redirect.

This parameter is optional. If it is not provided, there is only a notification
message at the end of the authentication process, as before, and the user is
not redirected when visiting the authentication domain while already
authenticated.

### CODE REVIEW

**Comment by jmccoy555** [comment]
Hi @clems4ever 

I think this has broken something. I've just pulled the latest docker develop (from 9 hours ago which alights to this merge) and I'm getting stuck in a login loop between the first and second stage, first stages succeeds, but the second says I'm not logged in. 

Will have to investigate a bit more later, hopefully today.

**Comment by clems4ever** [comment]
Hello @jmccoy555 , the integration tests were all green and the feature is definitely tested, this is weird. I'll pay attention to this while developing new features. If you find how to reproduce before I do, it would be awesome if you can open a new ticket to give details on the test case.

What do you think about the feature, btw?

Thank you.

**Comment by jmccoy555** [comment]
Hi @clems4ever 

I've just tried again with the latest develop (just in case there was something odd going on for some reason) and still no luck. Here's my log from a single log in attempt. Any thoughts so I can investigate and open a ticket if necessary, there are a few 'undefined' enteries?

I've checked my Authelia and nginx config against the develop branch and everything looks good to me. 

info: date='Fri Oct 20 2017 07:58:54 GMT+0000 (UTC)' message='Listening on port 80...'
debug: date='Fri Oct 20 2017 07:59:38 GMT+0000 (UTC)' method='GET', path='/' requestId='d7180888-a591-4919-9f84-8a7ee3a48003' sessionId='8GD6SmCUaXLAuDoFCXu_zzC1F8sC6oIs' ip='::ffff:10.20.1.2' message='Headers = {"x-original-uri":"/","host":"auth.my.domain","x-real-ip":"10.10.10.37","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.52 Safari/537.36","upgrade-insecure-requests":"1","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"connect.sid=s%3AscQ8SHGoXK4tp3R11l_MnuGxK3dSEP7G.WS78Smkz3mxFbweIX1CpC6eWj0E8hPyQR3XooZ8qrrs","if-none-match":"W/\"62d-DKKmhxgE4YmdWt2m7kCRHsYI2b4\""}'
debug: date='Fri Oct 20 2017 07:59:38 GMT+0000 (UTC)' method='GET', path='/' requestId='d7180888-a591-4919-9f84-8a7ee3a48003' sessionId='8GD6SmCUaXLAuDoFCXu_zzC1F8sC6oIs' ip='::ffff:10.20.1.2' message='Authentication session 8GD6SmCUaXLAuDoFCXu_zzC1F8sC6oIs was undefined. Resetting.'
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='87a4a48d-d915-4dc8-9beb-81a971fa3473' sessionId='P8InZLsbrStViuY5YgrIOYgI9PDBUIWS' ip='::ffff:10.20.1.2' message='Headers = {"x-original-uri":"/api/firstfactor","host":"auth.my.domain","x-real-ip":"10.10.10.37","connection":"close","content-length":"37","accept":"*/*","origin":"https://auth.my.domain","x-requested-with":"XMLHttpRequest","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.52 Safari/537.36","content-type":"application/x-www-form-urlencoded; charset=UTF-8","referer":"https://auth.my.domain/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"connect.sid=s%3AscQ8SHGoXK4tp3R11l_MnuGxK3dSEP7G.WS78Smkz3mxFbweIX1CpC6eWj0E8hPyQR3XooZ8qrrs"}'
info: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='87a4a48d-d915-4dc8-9beb-81a971fa3473' sessionId='P8InZLsbrStViuY5YgrIOYgI9PDBUIWS' ip='::ffff:10.20.1.2' message='Starting authentication of user "james"'
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='87a4a48d-d915-4dc8-9beb-81a971fa3473' sessionId='P8InZLsbrStViuY5YgrIOYgI9PDBUIWS' ip='::ffff:10.20.1.2' message='Authentication session P8InZLsbrStViuY5YgrIOYgI9PDBUIWS was undefined. Resetting.'
info: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='87a4a48d-d915-4dc8-9beb-81a971fa3473' sessionId='P8InZLsbrStViuY5YgrIOYgI9PDBUIWS' ip='::ffff:10.20.1.2' message='No regulation applied.'
debug: LDAP: Bind user 'cn=administrator,cn=users,dc=my,dc=lan'
debug: Computed users filter is sAMAccountName=james
debug: LDAP: searching for user dn of james
debug: LDAP: retrieved user dn is CN=James,CN=Users,DC=my,DC=lan
debug: LDAP: Bind user 'CN=James,CN=Users,DC=my,DC=lan'
debug: LDAP: Unbind user 'CN=James,CN=Users,DC=my,DC=lan'
debug: LDAP: Bind user 'cn=administrator,cn=users,dc=my,dc=lan'
debug: Computed users filter is sAMAccountName=james
debug: LDAP: searching for user dn of james
debug: LDAP: retrieved user dn is CN=James,CN=Users,DC=my,DC=lan
debug: LDAP: emails of user 'james' are james@my.domain
debug: Computed users filter is sAMAccountName=james
debug: LDAP: searching for user dn of james
debug: LDAP: retrieved user dn is CN=James,CN=Users,DC=my,DC=lan
debug: Computed groups filter is (&(member=CN=James,CN=Users,DC=my,DC=lan)(objectclass=group))
debug: LDAP: groups of user james are [users]
debug: LDAP: Unbind user 'cn=administrator,cn=users,dc=my,dc=lan'
info: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='87a4a48d-d915-4dc8-9beb-81a971fa3473' sessionId='P8InZLsbrStViuY5YgrIOYgI9PDBUIWS' ip='::ffff:10.20.1.2' message='LDAP binding successful. Retrieved information about user are {"emails":["james@my.domain"],"groups":["users"]}'
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='87a4a48d-d915-4dc8-9beb-81a971fa3473' sessionId='P8InZLsbrStViuY5YgrIOYgI9PDBUIWS' ip='::ffff:10.20.1.2' message='Authentication method for "" is "two_factor"'
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='87a4a48d-d915-4dc8-9beb-81a971fa3473' sessionId='P8InZLsbrStViuY5YgrIOYgI9PDBUIWS' ip='::ffff:10.20.1.2' message='Mark successful authentication to regulator.'
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='87a4a48d-d915-4dc8-9beb-81a971fa3473' sessionId='P8InZLsbrStViuY5YgrIOYgI9PDBUIWS' ip='::ffff:10.20.1.2' message='Redirect to '/secondfactor'' undefined
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='GET', path='/secondfactor' requestId='6c19ed54-e039-4fcb-a33a-708e046f393c' sessionId='GsnX6L7hBYGTptqekr9PWPz033pGQU1_' ip='::ffff:10.20.1.2' message='Headers = {"x-original-uri":"/secondfactor","host":"auth.my.domain","x-real-ip":"10.10.10.37","connection":"close","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.52 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://auth.my.domain/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"connect.sid=s%3AscQ8SHGoXK4tp3R11l_MnuGxK3dSEP7G.WS78Smkz3mxFbweIX1CpC6eWj0E8hPyQR3XooZ8qrrs","if-none-match":"W/\"3fa-adkr1eyb1E9jknA0ZIY0Xna0Mss\""}'
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='GET', path='/secondfactor' requestId='6c19ed54-e039-4fcb-a33a-708e046f393c' sessionId='GsnX6L7hBYGTptqekr9PWPz033pGQU1_' ip='::ffff:10.20.1.2' message='Authentication session GsnX6L7hBYGTptqekr9PWPz033pGQU1_ was undefined. Resetting.'
error: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='GET', path='/secondfactor' requestId='6c19ed54-e039-4fcb-a33a-708e046f393c' sessionId='GsnX6L7hBYGTptqekr9PWPz033pGQU1_' ip='::ffff:10.20.1.2' message='Reply with error 401: First factor has not been validated yet.'
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='GET', path='/secondfactor' requestId='6c19ed54-e039-4fcb-a33a-708e046f393c' sessionId='GsnX6L7hBYGTptqekr9PWPz033pGQU1_' ip='::ffff:10.20.1.2' message='FirstFactorValidationError: First factor has not been validated yet.
    at /usr/src/server/src/lib/FirstFactorValidator.js:10:43
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/src/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)'
debug: date='Fri Oct 20 2017 07:59:40 GMT+0000 (UTC)' method='GET', path='/error/401' requestId='edbf45cb-d136-421e-bd0d-e6d05e4ad175' sessionId='N-D4IViZM1FnG4LUNWcUwpBREDN9psl4' ip='::ffff:10.20.1.2' message='Headers = {"x-original-uri":"/secondfactor","host":"auth.my.domain","x-real-ip":"10.10.10.37","connection":"close","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.52 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://auth.my.domain/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"connect.sid=s%3AscQ8SHGoXK4tp3R11l_MnuGxK3dSEP7G.WS78Smkz3mxFbweIX1CpC6eWj0E8hPyQR3XooZ8qrrs","if-none-match":"W/\"3fa-adkr1eyb1E9jknA0ZIY0Xna0Mss\""}'

**Comment by clems4ever** [comment]
Hi @jmccoy555 , great news! Thanks.

**Pull request merged**
