### PR TITLE
Add Support for Private Certificate Authority Signed LDAPS Server Certificates

### PR DESCRIPTION
**Pull request by rajha-korithrien**
What this pull request does:
* Provides users the ability to specify the CA of their ldaps server when such server uses a private CA. 
* Added some info and debug logging to understand how Authelia initializes the TLS system in ldapjs

Why do we need it:
* Not all ldaps servers will use a certificate signed by a publicly trusted CA. For example: in corporate environments with an existing authentication stack, or in a Kubernetes environment where the ldaps server uses a certificate signed by the cluster CA
* The logging makes it easier to track what is going on when setting up an ldaps backend.

Risks:
The version of Node was moved from the 8.x branch to the 10.x branch which uses an improved TLS stack. The resulting Docker image has been tested in:
* ldaps with publicly trusted CA (which was working before and continues to work)
* ldaps with a private CA (which was not working before and is working now)
* ldap non-TLS configurations (which was working before and continues to work).

Currently there is an issue with Node where certain self-signed certificates do not work which is addressed in nodejs/node#22906. This impacts the use of private CA Active Directory certificates, and the patch 22906 was tested to work with Authelia as well.

### CODE REVIEW

**Comment by clems4ever** [comment]
Hello @rajha-korithrien , thank you for the PR. Could you please squash the changes ?

**Comment by clems4ever** [comment]
It looks good, thank you for your awesome work. Let's wait for the tests to pass now.

**Comment by rajha-korithrien** [comment]
> squash the changes

@clems4ever Understood, I will go learn how to squash changes :-)

**Comment by rajha-korithrien** [comment]
The git history for the source branch of this pull request is very dirty as @clems4ever pointed out.
I will create a new pull request with a clean branch.

**Comment by rajha-korithrien** [comment]
Please consider #375 instead of this pull request as 375 is from a much cleaner branch :-)

**Pull request closed without merging**
