### PR TITLE
Adding Theming

### PR DESCRIPTION
**Pull request by BankaiNoJutsu**
In reply to: https://github.com/clems4ever/authelia/issues/285

Major changes include:
- Added 4 themes, plus the default one.
    - "themes" folder is holding the files. One folder for each theme.
    - README in themes folder on usage/creation.
- Added --theme= switch to the gruntfile to choose which theme to build. Default is on "default".
    - Any unknown theme name will be rejected with according message.
- Added dependency for grunt-contrib-clean.
    - Clean backup folder, copy dist folder to backup, clean dist folder before build.

I have tested the docker-build, image was created. However I have not had time to run it.
I have not tested kubernetes either.

My tests were all successfull. Please test it as well. Thanks!

### CODE REVIEW

**Comment by clems4ever** [comment]
@BankaiNoJutsu , thank you for this huge contribution. I'll have a look soon! :)

**Comment by clems4ever** [comment]
I'm testing the change right now.

**Comment by clems4ever** [comment]
I love the black theme, it's so nice!

**Comment by BankaiNoJutsu** [comment]
Cool you like it! :) Still some things to fix like, E-Mail template for password reset and clean up. Also doing a script to install themes without needing to recompile the whole Server everytime

**Pull request merged**
