### PR TITLE
Ux enhancement

### PR DESCRIPTION
**Pull request by clems4ever**
Enhance:
- second factor page (unified second factor)
- TOTP registration page (Rename TOTP into One-time password, add links to Google Authenticator)
- Email subjects (Do not use U2F and TOTP acronyms in subject)
- UI (Visually split header and body)

### CODE REVIEW

**Comment by clems4ever** [comment]
Treats most of #145.

**Comment by jmccoy555** [comment]
Hi @clems4ever 

I've just tried to build this locally but it's failing??? I presume it should build with the following command;

mcy@DOCK001:/file001/dev/authelia$ docker build --tag=clems4ever/authelia:ux .
Sending build context to Docker daemon  4.518MB
Step 1/11 : FROM node:8.7.0-alpine
 ---> a47a5669ac57
Step 2/11 : WORKDIR /usr/src
 ---> Using cache
 ---> 9c21676a3d42
Step 3/11 : COPY package.json /usr/src/package.json
 ---> Using cache
 ---> 63d3b506aa35
Step 4/11 : RUN apk --update add --no-cache --virtual       .build-deps make g++ python &&     npm install --production &&     apk del .build-deps
 ---> Using cache
 ---> 8f753728d41b
Step 5/11 : COPY dist/server /usr/src/server
lstat dist/server: no such file or directory

**Comment by clems4ever** [comment]
@jmccoy555, have you run a `grunt build` before building the image? I generates the `dist/server` directory and the docker build will use it to build the image.

**Comment by jmccoy555** [comment]
@clems4ever Urrrmmmm, nope. No idea what that's just done :confused: but it worked and the UI is looking nice, and the U2F is flashing nicely once passed the first factor!

And just found the auto-redirect after a few seconds, very nice. 

May have a slight issue, if you click one of the registration options, I'm getting an error 401 need to log in.

**Comment by clems4ever** [comment]
@jmccoy555 , great! And thank you for the feedback. 
If you have a reproducible test case, can you please create an issue and put it there?

**Comment by jmccoy555** [comment]
@clems4ever Does this look like something to worry about?

error: date='Sun Oct 22 2017 12:34:07 GMT+0000 (UTC)' method='GET', path='/secondfactor/u2f/identity/start' requestId='c99e8dfa-88e2-4cbc-88e5-5c2c10bc4be2' sessionId='J4GFrEKFE4cUrXIztKr3csdVJsDKXTK4' ip='::ffff:10.20.1.2' message='Reply with error 401: Error while sending email: unable to verify the first certificate'
debug: date='Sun Oct 22 2017 12:34:07 GMT+0000 (UTC)' method='GET', path='/secondfactor/u2f/identity/start' requestId='c99e8dfa-88e2-4cbc-88e5-5c2c10bc4be2' sessionId='J4GFrEKFE4cUrXIztKr3csdVJsDKXTK4' ip='::ffff:10.20.1.2' message='Error: Error while sending email: unable to verify the first certificate
    at that.transporter.sendMail (/usr/src/server/src/lib/notifiers/MailSender.js:26:28)
    at transporter.send.args (/usr/src/node_modules/nodemailer/lib/mailer/index.js:224:21)
    at SMTPConnection.connection.once.err (/usr/src/node_modules/nodemailer/lib/smtp-transport/index.js:174:24)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at SMTPConnection.emit (events.js:210:7)
    at SMTPConnection._onError (/usr/src/node_modules/nodemailer/lib/smtp-connection/index.js:581:14)
    at TLSSocket._socket.on.err (/usr/src/node_modules/nodemailer/lib/smtp-connection/index.js:702:46)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)'

**Pull request merged**
