### PR TITLE
Make notifications appear on top instead of inline

### PR DESCRIPTION
**Pull request by naggie**
Currently notifications reflow the document which causes the interface
to jump twice which can be frustrating if you're trying to click
something.

This change makes the notification appear at the top of the form as
such:

image

@clems4ever do you agree with this? If not feel free to discard this PR.

### CODE REVIEW

**Comment by clems4ever** [comment]
I think those failing tests are not related to your change, I have the same failures on my PR and I don't yet understand why. I'll have a look.

**Comment by clems4ever** [comment]
The code is ok for me, there is only a missing space between the links to register devices in second factor page. Please fix it and I will merge the PR.

**Comment by clems4ever** [comment]
2018-07-26-004645_1920x1080_scrot

**Comment by naggie** [comment]
Ah -- it seems that I removed the important whitespace when running a whitespace remover. Fixed -- thanks

**Pull request merged**
