### PR TITLE
Refactor client to make it responsive and testable

### PR DESCRIPTION
**Pull request by clems4ever**
* Rewrite client in typescript
* Make client responsive
* Improve UI
* Add tests to the client
* Update endpoints

### CODE REVIEW

**Comment by clems4ever** [comment]
email_confirmation
first_factor
reset_password

totp
u2f

**Comment by jkaberg** [comment]
@clems4ever Just a thought - better not to use Gmail logo (replace it with something generic)? Might upset Google, and it kinda "locks you in" for one notification provider  when later on one might introduce several others (eg. SMTP, Push etc.)

Just a thought :smile: Awesome work otherwise!

**Comment by clems4ever** [comment]
Hello @jkaberg , you are right. I will find another icon. Thank you for your feedback.

**Comment by clems4ever** [comment]
Hello @jkaberg, I changed the mail icon :)
image

**Comment by jkaberg** [comment]
@clems4ever Much better! 😄

**Pull request merged**
